// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejiovpsulejqlrqruwwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqaW92cHN1bGVqcWxycXJ1d3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTk0MTAsImV4cCI6MjA2NDA3NTQxMH0.62NnSA6k-N0etp9-m1j0AUTeXJBtiw2A6T8MlylAPnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);